name: Lint

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ruff
        run: pipx install ruff
      - name: Ruff check
        run: ruff check custom_components/triad_ams

